version: '3.8'

services:
  database:
    image: mongo:latest
    container_name: streamit_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    container_name: streamit_api
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://database:27017/streamit
      - TMDB_API_KEY=${TMDB_API_KEY}
      - WATCHMODE_API_KEY=${WATCHMODE_API_KEY}
    depends_on:
      - database

  client:
    build: ./client
    container_name: streamit_client
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  mongo_data:
